// Original short lines written for Missy. No external sourcing.
export const DEFAULT_QUOTES = [
  "You showed up today. That's the whole game.",
  "Progress doesn't ask for perfect, just present.",
  "Small done beats big planned.",
  "Tomorrow gets easier because today happened.",
  "You moved the day forward, even the messy parts.",
  "Rest counts as part of the work.",
  "One honest step beats ten imagined ones.",
  "You don't need a perfect score to have a good day.",
  "The list is a guide, not a grade.",
  "Every word you learned today is yours to keep.",
  "An idea written down is a future you didn't have to think of twice.",
  "Momentum is built in ordinary hours like this one.",
  "You kept a promise to yourself today.",
  "Unfinished isn't the same as failed.",
  "The plan flexed and you flexed with it.",
  "Some days are for building, some are for holding steady. Both count.",
  "You paid attention today. That's rarer than it sounds.",
  "Nobody sees the effort behind the checkmark, but it's real.",
  "You gave today a shape instead of letting it happen to you.",
  "Consistency is quieter than intensity, and it wins more often.",
  "The version of you tomorrow inherits what you did today.",
  "You chose to track this. That's already discipline.",
  "A day with one good idea is not a wasted day.",
  "Skipped isn't the opposite of done, it's just information for next time.",
  "You're allowed to be proud of an ordinary Tuesday.",
  "Small habits compound quietly until they don't.",
  "The best schedule is the one you actually followed some of.",
  "You put words to what you were thinking. That matters.",
  "Every rep, even a half one, still counts as a rep.",
  "You didn't wait for motivation, you just started.",
  "Today's effort doesn't need an audience to be real.",
  "A slower day is still a day you were awake for your own life.",
  "You noticed what you learned. Most people don't.",
  "The gap between plan and reality is where real life happens.",
  "You're building a track record with yourself.",
  "Being gentle with today makes tomorrow more likely to happen well.",
  "One more word learned is one more door you can open later.",
  "You closed the loop on something today. That's momentum.",
  "The score is a mirror, not a judge.",
  "You did the thing that was actually possible today, not the ideal one.",
  "A day of learning is never a day wasted, even without a checklist to prove it.",
  "You kept talking to yourself in the mornings, that's how habits form.",
  "The fact that you're reviewing this means you're already ahead of most days.",
  "You turned a rough sketch of a day into something real.",
  "Some tasks move mountains, some just keep the lights on. Both matter.",
  "You are allowed to redefine 'good day' as you go.",
  "The words you're collecting are quietly becoming a bigger vocabulary of thought.",
  "You showed up for your own plans today, and that's not nothing.",
  "Today's leftovers are tomorrow's head start.",
  "You made a decision and lived inside it for a day. That's steering, not drifting.",
  "Every idea you capture is a seed you don't have to regrow.",
  "You don't owe today a perfect performance.",
  "The plan was a hypothesis. Today was the experiment.",
  "You're allowed to close the day without finishing the list.",
  "A day with effort in it is already a successful one.",
  "You practiced showing up, which is the actual skill.",
  "Some of today's work won't show up until much later. Keep going anyway.",
  "You gave your morning intention before the day could hand you its own.",
  "The gap between who you were this morning and now is real, even if small.",
  "You chose structure over drift today, and that's a quiet kind of courage.",
  "Learning one new word is a permanent upgrade to how you think.",
  "You're not behind, you're just mid-story.",
  "A day of half-progress still moves the average up.",
  "The fact you tried to plan this morning already changed how today went.",
  "You're allowed to call today enough.",
  "Every task attempted, even unfinished, taught you something about your own pace.",
  "You spent today being a person who tries. That adds up.",
  "The habit is the win, the outcome is just a bonus.",
  "You gave your ideas somewhere to land today instead of vanishing.",
  "Today you practiced finishing things, which is its own separate skill from starting them.",
  "You don't need every day to be a personal best to be building something real.",
  "The work you did today doesn't need to be seen to have counted.",
  "You are the only person who needs to know how hard today actually was.",
  "A quieter day of steady effort beats a loud day of burnout.",
  "You kept your own appointment with your own goals today.",
  "The words, ideas, and tasks you logged are proof you were paying attention to your own life.",
  "You don't have to feel motivated to have been productive.",
  "Today you practiced trusting a plan you made for yourself this morning.",
  "Some of what you did today will only make sense in hindsight.",
  "You're allowed to grade today on effort, not just output.",
  "The score resets tomorrow. The habit doesn't have to.",
  "You made today legible to your future self.",
  "A single completed task, chosen honestly, beats ten abandoned ambitions.",
  "You kept a small promise today, and small promises are how trust with yourself is built.",
  "Today's plan met today's reality, and you adjusted instead of quitting.",
  "You are not required to feel finished to be finished for today.",
  "The vocabulary you're building is a long game paying off in small daily deposits.",
  "You turned rambling thoughts into an actual plan this morning. That's a skill.",
  "Every idea logged today is a door left open instead of closed.",
  "You practiced the muscle of intention today, which matters more than any single outcome.",
  "A day that ends in review is a day that's actually being lived on purpose.",
  "You don't need to outperform yesterday, just show up like today.",
  "The plan bent, you didn't break. That's the actual win.",
  "You gave shape to a day that could have just slipped by unnoticed.",
  "Today counts, even the part where you fell behind and kept going anyway.",
  "You're allowed to be both tired and proud right now.",
  "Every word, idea, and task tonight is evidence you were awake to your own life today.",
  "The habit of reviewing your day is already rarer than the habit of having a perfect one.",
  "You made it to the end of today with intention. That's the real metric.",
  "Tomorrow morning, you get to try again with everything you learned today.",
  "You are, right now, someone who follows through on checking in with themselves.",
];
